### ISSUE TITLE
Execute harmony call in UAT

### ISSUE THREAD

**Issue by frankinspace** [podaac/bignbit#33]
Test that harmony call returns a png image when specifying the OPERA_L3_DSWX-S1_V1 collection

**Comment by torimcd** [comment]
This will be closed by https://github.com/podaac/bignbit-config/pull/3. Need to update the collection config to add height, width parameters. With manually updated config, submit_harmony_job lamdba completes successfully. Overall workflow fails on copy_harmony_results step though due to incorrect module name, which was discussed to be fixed prior to 0.2.0. We should verify this again to ensure workflow completion prior to 0.2.0 release.
